In [1]:
!pip install wikipedia-api


In [2]:
import numpy as np
import tensorflow as tf
import wikipediaapi
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense, Dropout
from tensorflow.keras.utils import to_categorical


2024-05-06 10:50:50.261115: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-05-06 10:50:50.261228: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-05-06 10:50:50.395417: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


In [3]:
# Fetch Wikipedia article
def fetch_wikipedia_text(topic):
      wiki_wiki = wikipediaapi.Wikipedia(
      language='en',
      extract_format=wikipediaapi.ExtractFormat.WIKI,
      user_agent='my-application/1.0')
      page = wiki_wiki.page(topic)
      return page.text

# Preprocess text
def preprocess_text(text):
    # Convert to lowercase
    text = text.lower()
    # Remove special characters
    text = ''.join(c for c in text if c.isalnum() or c in [' ', '\n'])
    return text

In [4]:
topic = "Artificial intelligence"
wikipedia_text = fetch_wikipedia_text(topic)
preprocessed_text = preprocess_text(wikipedia_text)
print(preprocessed_text)


artificial intelligence ai in its broadest sense is intelligence exhibited by machines particularly computer systems it is a field of research in computer science that develops and studies methods and software which enable machines to perceive their environment and uses learning and intelligence to take actions that maximize their chances of achieving defined goals such machines may be called ais
ai technology is widely used throughout industry government and science some highprofile applications include advanced web search engines eg google search recommendation systems used by youtube amazon and netflix interacting via human speech eg google assistant siri and alexa autonomous vehicles eg waymo generative and creative tools eg chatgpt and ai art and superhuman play and analysis in strategy games eg chess and go however many ai applications are not perceived as ai a lot of cutting edge ai has filtered into general applications often without being called ai because once something becom

In [5]:
# Create character-to-integer mapping
chars = sorted(list(set(preprocessed_text)))
char_to_int = {c: i for i, c in enumerate(chars)}
int_to_char = {i: c for i, c in enumerate(chars)}

# Convert characters to numerical representations
encoded_text = [char_to_int[c] for c in preprocessed_text]

# Define sequence length
seq_length = 100
# Generate sequences
sequences = []
for i in range(0, len(encoded_text) - seq_length, 1):
    sequences.append(encoded_text[i:i + seq_length + 1])

# Convert sequences to numpy arrays
X = np.array([seq[:-1] for seq in sequences])
y = np.array([seq[-1] for seq in sequences])
print(X )
print("------------------------------------------------------------------------------------------")
print(y)


[[12 29 31 ... 23 36  1]
 [29 31 20 ... 36  1 14]
 [31 20 17 ...  1 14 26]
 ...
 [16 22 30 ... 15 20 14]
 [22 30 12 ... 20 14 20]
 [30 12 25 ... 14 20 25]]
------------------------------------------------------------------------------------------
[14 26 24 ... 20 25 16]


In [6]:
# Build the model
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(len(chars), 50, input_length=seq_length),
    tf.keras.layers.SimpleRNN(256, return_sequences=True),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.SimpleRNN(256),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(len(chars), activation='softmax')
])

# Compile the model
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam')

# Train the model
model.fit(X, y, batch_size=64, epochs=50)


/opt/conda/lib/python3.10/site-packages/keras/src/layers/core/embedding.py:86: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Epoch 1/50
   7/1106 ━━━━━━━━━━━━━━━━━━━━ 24s 22ms/step - loss: 3.8482 

I0000 00:00:1714992671.269335      90 device_compiler.h:186] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


1106/1106 ━━━━━━━━━━━━━━━━━━━━ 35s 25ms/step - loss: 3.5090
Epoch 2/50
1106/1106 ━━━━━━━━━━━━━━━━━━━━ 24s 21ms/step - loss: 3.0250
Epoch 3/50
1106/1106 ━━━━━━━━━━━━━━━━━━━━ 24s 21ms/step - loss: 2.9882
Epoch 4/50
1106/1106 ━━━━━━━━━━━━━━━━━━━━ 24s 22ms/step - loss: 2.9840
Epoch 5/50
1106/1106 ━━━━━━━━━━━━━━━━━━━━ 24s 21ms/step - loss: 2.9796
Epoch 6/50
1106/1106 ━━━━━━━━━━━━━━━━━━━━ 24s 21ms/step - loss: 2.9846
Epoch 7/50
1106/1106 ━━━━━━━━━━━━━━━━━━━━ 24s 22ms/step - loss: 2.9789
Epoch 8/50
1106/1106 ━━━━━━━━━━━━━━━━━━━━ 24s 22ms/step - loss: 2.9858
Epoch 9/50
1106/1106 ━━━━━━━━━━━━━━━━━━━━ 24s 21ms/step - loss: 2.9860
Epoch 10/50
1106/1106 ━━━━━━━━━━━━━━━━━━━━ 24s 22ms/step - loss: 3.0086
Epoch 11/50
1106/1106 ━━━━━━━━━━━━━━━━━━━━ 24s 22ms/step - loss: 2.9939
Epoch 12/50
1106/1106 ━━━━━━━━━━━━━━━━━━━━ 24s 22ms/step - loss: 2.9817
Epoch 13/50
1106/1106 ━━━━━━━━━━━━━━━━━━━━ 24s 22ms/step - loss: 2.9265
Epoch 14/50
1106/1106 ━━━━━━━━━━━━━━━━━━━━ 24s 21ms/step - loss: 2.8456
Epoch 15/50


In [7]:
def generate_text_base_char(model, seed_text, num_chars=100, seq_length=100):
    # Preprocess the seed text
    seed_text = preprocess_text(seed_text)
    generated_text = seed_text

    for _ in range(num_chars):
        # Convert seed text to numerical representation
        encoded_seed = [char_to_int.get(char, 0) for char in seed_text]  # Use `get` with a default value if char not found

        # Padding if necessary
        if len(encoded_seed) < seq_length:
            padding = [0] * (seq_length - len(encoded_seed))  # Assuming '0' is used for padding
            encoded_seed = padding + encoded_seed

        encoded_seed = np.array([encoded_seed[-seq_length:]])  # Ensure input is exactly `seq_length` long

        # Predict the next character
        predicted_probs = model.predict(encoded_seed)[0]
        predicted_index = np.random.choice(len(predicted_probs), p=predicted_probs)
        predicted_char = int_to_char[predicted_index]

        # Add predicted character to the generated text
        generated_text += predicted_char

        # Update seed text for next prediction
        seed_text += predicted_char
        seed_text = seed_text[1:]  # Sliding window

    return generated_text

seed_text = "Neural"
generated_text = generate_text_base_char(model, seed_text)
print(generated_text)


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 554ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
1/1 ━━━━━━━

In [8]:
text = preprocessed_text
# Prepare the tokenizer and encode the words
tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])
encoded = tokenizer.texts_to_sequences([text])[0]
vocab_size = len(tokenizer.word_index) + 1

# Generate sequences
seq_length = 100
sequences = []
for i in range(seq_length, len(encoded)):
    seq = encoded[i-seq_length:i+1]
    sequences.append(seq)

sequences = np.array(sequences)
X, y = sequences[:,:-1], sequences[:,-1]
y = to_categorical(y, num_classes=vocab_size)






In [9]:
# Define the RNN model
model = Sequential([
    Embedding(vocab_size, 50, input_length=seq_length),
    SimpleRNN(256, return_sequences=True),
    Dropout(0.5),
    SimpleRNN(256),
    Dropout(0.5),
    Dense(vocab_size, activation='softmax')
])

# Compile the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
model.fit(X, y, batch_size=64, epochs=150)

Epoch 1/150
  6/171 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - accuracy: 0.0020 - loss: 7.9572    

W0000 00:00:1714993900.244275      88 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update


171/171 ━━━━━━━━━━━━━━━━━━━━ 14s 44ms/step - accuracy: 0.0312 - loss: 7.3737
Epoch 2/150
171/171 ━━━━━━━━━━━━━━━━━━━━ 4s 22ms/step - accuracy: 0.0350 - loss: 6.9628
Epoch 3/150
171/171 ━━━━━━━━━━━━━━━━━━━━ 4s 22ms/step - accuracy: 0.0361 - loss: 6.9855
Epoch 4/150
171/171 ━━━━━━━━━━━━━━━━━━━━ 4s 22ms/step - accuracy: 0.0386 - loss: 6.9457
Epoch 5/150
171/171 ━━━━━━━━━━━━━━━━━━━━ 4s 22ms/step - accuracy: 0.0411 - loss: 6.9359
Epoch 6/150
171/171 ━━━━━━━━━━━━━━━━━━━━ 4s 22ms/step - accuracy: 0.0402 - loss: 6.8677
Epoch 7/150
171/171 ━━━━━━━━━━━━━━━━━━━━ 4s 22ms/step - accuracy: 0.0201 - loss: 7.8285
Epoch 8/150
171/171 ━━━━━━━━━━━━━━━━━━━━ 4s 22ms/step - accuracy: 0.0395 - loss: 7.0681
Epoch 9/150
171/171 ━━━━━━━━━━━━━━━━━━━━ 4s 22ms/step - accuracy: 0.0373 - loss: 6.9915
Epoch 10/150
171/171 ━━━━━━━━━━━━━━━━━━━━ 4s 22ms/step - accuracy: 0.0366 - loss: 7.0037
Epoch 11/150
171/171 ━━━━━━━━━━━━━━━━━━━━ 4s 22ms/step - accuracy: 0.0360 - loss: 7.0204
Epoch 12/150
171/171 ━━━━━━━━━━━━━━━━━━━━

In [10]:
# Generate text function
def generate_text_base_word(model, tokenizer, seed_text, num_words):
    result = []
    in_text = seed_text
    for _ in range(num_words):
        encoded = tokenizer.texts_to_sequences([in_text])[0]
        encoded = pad_sequences([encoded], maxlen=seq_length, truncating='pre')
        yhat = model.predict(encoded, verbose=0)
        yhat = np.argmax(yhat, axis=1)
        out_word = ''
        for word, index in tokenizer.word_index.items():
            if index == yhat:
                out_word = word
                break
        in_text += ' ' + out_word
        result.append(out_word)
    return ' '.join(result)

# Example usage
seed_text = "Neural"
generated_text = generate_text_base_word(model, tokenizer, seed_text, 50)
print(seed_text,generated_text)

Neural and the problem of the problem to build the goal of the problem to build the near of the leaders of the copyrighted interpretable values justice and the physical symbol and the same own the openings odyssey the 13 professionals in 31 cooperation of irrelevant and the question of what
